name = "FirstAndLastPlaceValues"
author = "Jeffrey Sarnoff <jeffrey.sarnoff@gmail.com>"
uuid = "dd8a906a-23bc-4472-934d-9c54f090218b"
version = "0.1.0"

[compat]
Test  = "1.11"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
